module.exports = [
  'ept-posts',
  'ept-threads',
  'ept-boards',
  'ept-categories',
  'ept-users',
  'ept-auth',
  'ept-frontend',
  'ept-reports',
  'ept-mentions',
  'ept-messages',
  'ept-watchlist',
  'ept-bbcode-parser',
  'ept-md-parser',
  'ept-portal',
  'ept-auto-moderation',
  'ept-ads',
  'ept-ignore-users'
];
